Company:   {
  FO:   {
    Securities:   {
      style.fill: '#d6edd5'
      app12873: Data Source
      app12875: Data Solar
    }
    Equities:   {
      app12874: Joesph
    }
  }
  2LOD:   {
    Finance:   {
      app12872: Trade pad
    }
    Risk:   {
      app12876: Data Solar
    }
  }
}
Company.FO.Equities.app12874 -> Company.FO.Securities.app12875: security reference
Company.FO.Equities.app12874 -> Company.2LOD.Risk.app12876: quotes
Company.FO.Securities.app12875 -> Company.FO.Securities.app12875: instructions
Company.FO.Equities.app12874 -> Company.2LOD.Finance.app12872: instructions
Company.FO.Securities.app12875 -> Company.FO.Equities.app12874: client master
Company.FO.Securities.app12875 -> Company.FO.Equities.app12874: allocations